version: '3.4'

services:
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "26110:80"
      - "26111:81"

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "26120:80"
      - "26121:81"

