version: '3.4'

services:
  catalogAPI:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=catalogDB;Database=CatalogDB;User Id=admin;Password=admin1234;
    ports:
      - "26110:80"
      - "26111:81"

  catalogDB:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "26112:5432"
    volumes:
      - catalogDbData:/var/lib/postgresql/data/

  basketAPI:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=basketDB;Database=BasketDB;User Id=admin;Password=admin1234;
    ports:
      - "26120:80"
      - "26121:81"

  basketDB:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "26122:5432"
    volumes:
      - basketDbData:/var/lib/postgresql/data/

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  catalogDbData:
    external: false
  basketDbData:
    external: false